code_produto:
    resource: "@CodeProdutoBundle/Controller/"
    type:     annotation
    prefix:   /

code_car:
    resource: "@CodeCarBundle/Controller/"
    type:     annotation
    prefix:   /cars/

app:
    resource: @AppBundle/Controller/
    type:     annotation
